# Made by Terpz710 :p

# Available tag:
# {player} = Player Name
# {date} = Date (M/D/Y)
# Do not add anymore lines!
# Signs has a default of 4 lines
sign_text:
  - "RIP {player}"
  - ""
  - ""
  - "{date}"